### ISSUE TITLE
Maybe you need to add onSubmit: onTextSubmit in ChatInputFieldContainerWidget

### ISSUE THREAD

**Issue by nitosoftsystem** [MOUKZ/chat_package#5]
Its an awesome plugin, and I have test it and its work!!! Just maybe you forgot this line. :)
Version 1.0.0 beta

**Comment by MOUKZ** [comment]
thank you so much for the feedback <3
I'm still working on flutter 3 migration and adding some new features and bug fixes 
that's why it's in beta

**Comment by nitosoftsystem** [comment]
Waiting your next release.
